<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.1.13-beta09</Version>
    <Description>ParameterCollection is a simple to use collection for different parameters and types defined with a key. It supports many of the standard types like int, string, double, float, long, DateTime, bool, byte[], enums and more. It can also support nearly every other objects by easy converting the object to it´s own ParameterCollection, which can be nested togheter as parameters. It also supports many of the parameters as IEnumerables (List, Array, etc.). Methods to convert to and from JSON is also included.</Description>
    <PackageReleaseNotes>
        - Added the posssibillity to get values by paths.
        - Added PathMappingEngine to help mapping between ParameterCollections.
        - Fixed a bug that caused that when null values, it crashed even when the return type supported null values when calling ParameterCollection.GetByKey(..)
        - Breaking Change: Renamed ParameterConverterExtensions to ParameterCollectionExtensions.
        - Added the possibillity to convert list of ParameterCollection to simple json.
        - Added the possibillity to convert any json to a list of ParameterCollection.
        - Added AdditionalInfoParameterPropertyAttribute, so it is possible to say that property x should be gotten from the additionalInfo from another property and set in that additionalInfo.
        - ParameterCollectionParameterConverter will now automatically return null if value is null. This so both no problem should arise and you do not need to check if a value is null if you use this abstract class. If you for some reason you still to do some custom things if value is null, you can still use IParameterValueConverter directly.
        - Added the possibillity to handle how enums are handled when converting to simple json. You can now also define how the parameters of SelectOne, SelectMany and evt. Enum is named in the json-payload.
    </PackageReleaseNotes>
    <Authors>Yngve J. K. Hestem</Authors>
    <Copyright>Copyright (c) Yngve J. K. Hestem 2023</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>UI, parameter ParameterCollection collection parameters collections multiple-types-in-collection json key-value key-value-pair</PackageTags>
    <SynchReleaseVersion>false</SynchReleaseVersion>
    <RepositoryUrl>https://github.com/HeruEwasham/GenericParameterCollection.git</RepositoryUrl> 
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Newtonsoft.Json" />
    <None Remove="ParameterValueConverters\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ParameterValueConverters\" />
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
